### PR TITLE
Attempt to do OTA via SSL (non BPP)

### PR DESCRIPTION
**Pull request by annejan**

### CODE REVIEW

**Comment by annejan** [comment]
Currently crashes for me after nearly getting there . . 
I'm pretty sure this is a partitioning issue.

```
...
I (52095) ota: 1024 bytes read
I (52095) ota: Have written image length 1048441
I (52095) ota: 1024 bytes read
E (52095) ota: Error: esp_ota_write failed! err=0x104
E (52095) ota: Exiting task due to fatal error...
```

**Comment by annejan** [comment]
Works like a charm, only issue now is in the micropython firmware partition handling . .

**Comment by annejan** [comment]
Fixed by setting `esp_flash_user_start` to `0xB20000`

**Comment by basvs** [comment]
> #define BADGE_OTA_WEB_URL "https://badge.sha2017.org/firmware.bin"

I would define BADGE_OTA_WEB_PATH (as "/firmware.bin"), not BADGE_OTA_WEB_URL. In the http-request, you should use the path without the hostname.

> static int sha2017_ota_read_until(char *buffer, char delim, int len)
￼
Why not use memchr() or memmem()? (btw, http-servers *always* use "\r\n"). It would be nice to read the http status line (is 200? or 404? or something else?) and the Content-Length header. Not being strict can cause headaches when debugging issues.

> assert(configured == running); /* fresh from reset, should be running from configured boot partition */

I don't know if the boot-firmware can detect corrupted ota partitions. Is it possible that we are the boot-firmware? Until we know for sure, or have a more safe solution, we can keep the assert().

> mbedtls_ssl_conf_authmode(&conf, MBEDTLS_SSL_VERIFY_REQUIRED);
> …
> if ((flags = mbedtls_ssl_get_verify_result(&ssl)) != 0)

If I understood correctly, the certificate is always verified with MBEDTLS_SSL_VERIFY_REQUIRED. Could remove the ssl_get_verify_result or change it into an assert.

> err = esp_ota_begin(update_partition, OTA_SIZE_UNKNOWN, &update_handle);

We should only start OTA updates if the HTTP request doesn't return with an error. Should also check if the partition is large enough for the data to receive.
￼
> err = esp_ota_set_boot_partition(update_partition);

We should first verify that the ota data is correct. We could use a crc32 check, a sha hash or a signature. The last one also protects against TLS-implementation bugs and badge.sha2017.org server compromise.

> esp_err_t err = nvs_flash_init();
> if (err == ESP_ERR_NVS_NO_FREE_PAGES) {

This sounds like an ugly hack. Do we really need this? And isn't it better to keep all NVS data? (It probably contains some user preferences)


￼

**Comment by basvs** [comment]
I was just reading the bootloader code. If we keep the factory partition, the badge will auto-update if both OTA partitions got corrupted for some reason..

**Comment by annejan** [comment]
@basvs I'd like to finalise the partitions soon, @Spritetm you said something about the 64K block going out? What is your opinion about having a factory FW and 2 OTA's?

**Comment by annejan** [comment]
I would like to suggest tossing out my work and going for https://github.com/classycodeoss/esp32-ota-https as a basis..

Also has revision metadata . . 

https://blog.classycode.com/secure-over-the-air-updates-for-esp32-ec25ae00db43

**Pull request merged**
